### ISSUE TITLE
Implement data upload in Python client and document usage

### ISSUE THREAD

**Issue by banesullivan** [ResonantGeoData/RGD-ScrumBoard#29]
Tasks in Resonant GeoData:

- [x] Give users a default collection: https://github.com/ResonantGeoData/ResonantGeoData/issues/474
- [x] Add ability to upload new `ChecksumFile`s via the Python client (for now, assume URL/S3 files)
    - Give the ability to set the collection, otherwise, the user's default is used
- [x] Add ability to upload new imagery via Python client
- [x] Expand on https://github.com/ResonantGeoData/ResonantGeoData/pull/457 to better support uploading processed imagery

Tasks in downstream project (RD-WATCH):

- [ ] https://github.com/ResonantGeoData/RD-WATCH/issues/2
- [x] https://github.com/ResonantGeoData/RD-WATCH/issues/3

For the tasks in RD-WATCH, we want to be able to do this from the Python client - perhaps now is the time to implement extensions/plug-ins?
